### ISSUE TITLE
Issues with TSTool access

### ISSUE THREAD

**Issue by jurentie** [OpenCDSS/cdss-lib-dmi-hydrobase-rest-java#20]
A user has been experiencing issues with using TSTool and it is most likely related to an apiKey issue. I previously tried to ensure that when no apiKey is specified that TSTool handles this easily and does not attempt to append apiKey to the url, however it appears this not happening in some cases.

This would be worth going back through and checking all urls to prevent this from happening with other situations.

See lines 7 and 8

```
1: Status[2](TSToolMain.openDataStoresAtStartup): Opening datastore using properties in "ColoradoHydroBaseRest.cfg".
2: Status[2](TSToolMain.openDataStore): DataStoreConfigFile=C:\CDSS\TSTool-12.06.00\system\ColoradoHydroBaseRest.cfg
3: Status[2](TSToolMain.openDataStore): Getting class for name "cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStoreFactory"
4: Status[2](TSToolMain.openDataStore): Creating instance of class "cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStoreFactory"
5: Status[2](ColoradoHydroBaseRestDataStore.determineAPIVersion): DWR REST services API version = 2
6: Warning[3](JacksonToolkit.getJsonNodeFromWebServices): Exception stack trace follows (see log file)...
7: Warning[3](JacksonToolkit.getJsonNodeFromWebServices): Server returned HTTP response code: 400 for URL: https://dnrweb.state.co.us/DWR/DwrApiService/api/v2/referencetables/county/?format=json&apiKey=
8: java.io.IOException: Server returned HTTP response code: 400 for URL: https://dnrweb.state.co.us/DWR/DwrApiService/api/v2/referencetables/county/?format=json&apiKey=
9:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
10:	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
11:	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
12:	at java.net.URL.openStream(Unknown Source)
13:	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1582)
14:	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:793)
15:	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2609)
16:	at cdss.dmi.hydrobase.rest.dto.JacksonToolkit.getJsonNodeFromWebServices(JacksonToolkit.java:47)
17:	at cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStore.readCounties(ColoradoHydroBaseRestDataStore.java:1840)
18:	at cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStore.readGlobalData(ColoradoHydroBaseRestDataStore.java:1911)
19:	at cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStore.<init>(ColoradoHydroBaseRestDataStore.java:582)
20:	at cdss.dmi.hydrobase.rest.ColoradoHydroBaseRestDataStoreFactory.create(ColoradoHydroBaseRestDataStoreFactory.java:30)
21:	at DWR.DMI.tstool.TSToolMain.openDataStore(TSToolMain.java:1150)
22:	at DWR.DMI.tstool.TSToolMain.openDataStoresAtStartup(TSToolMain.java:1323)
23:	at DWR.DMI.tstool.TSTool_JFrame.<init>(TSTool_JFrame.java:2400)
24:	at DWR.DMI.tstool.TSToolMain.main(TSToolMain.java:862)
25:	at cdss.app.tstool.TSTool.main(TSTool.java:28)
```

**Comment by smalers** [comment]
I have been cleaning up the way TSTool configuration is handled.  This should be improved in the next TSTool release.
